version: '3'

services:
  web:
    build: .
    # platform: linux/amd64
    ports:
      - "5002:5002"
    
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: flaskapp
    depends_on:
      - db

  db:
    image: mysql:8.0
    # platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flaskapp
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d/

volumes:
  db_data:
